version: '3'
services:
  profileservice:
    container_name: profileservice
    image: antonnv22/profileservice:0.0.7
    networks:
      - profilenetwork
    restart: always
    depends_on:
      - profiledb
    ports:
      - "8000:8000"
    environment:
      DB_HOSTNAME: profiledb
      DB_NAME: users
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
  profiledb:
    container_name: profiledb
    image: postgres:14.4
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - profilenetwork
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'Europe/Moscow'
networks:
  profilenetwork: