apiVersion: v1
data:
  jwt-private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDPqdJDSaR4XcpM
    e91dWZiTY/G3So0+lxN1FZh8+6FOGisV01RbaDNbJ8WWjT9L20JJWF3vUzd003bb
    RL3hA36RyioXZXkUOU5akCxVvpGOnnKh7I0H3hVfAx6B2ZEDZ4uEbz2dyAe7u+w+
    PGgCBx4tFs4dhjKlJQp1iu4I5sEoOpLQk7y/OqDzRuebbGYaTmAQqNKFrYNfHeHI
    AxJ+c4bUYT+vxbfnjvaSrVfTjObaK6gIJLCJ+JKLkYXguvWx4uJumtqL25y2SEQ7
    ZMl4eiXWwSI9ctIO7lc4gCHNSscuPHe3Ol5h0tLIbCGWrQM6W7LqEMCX8lH8bMSA
    S40FZNnbAgMBAAECggEARdscriHxv8PdL4ljV+mx17MBNuVPSkTL+NEA8No80uce
    o0Lp163fyMRCRXjSWBQz4jRltQJLX3NbQjuHnE/uneBh9GjgKBt27iQdpeJrWIyY
    hzvp3UGp8sI72vZzP6/vUOeS1KbbYx2+RNlRK411azmGsIvaMY+aSxwnIrttMriV
    sMgMwATHq9rC/0TTIz8SVQZsPsdgGVQ56p1ZKmwIhS8ttmk6Jz+tNaH7jjB9fkRQ
    rS6QdIjyFy+Mf0WY5j6k4sYcnqF9m5FIzpryZ+kFtoG24K54jU8SHMV4MpQ+PWDl
    WX3IBhcgGni4h21wCvDELqwNGFSvUyQXh90IwR8rkQKBgQD8pHfPYwZHybpMbPKD
    IzCC/HiiHQi8c4Sz0IR3H9mFjLw3ht47ilr8GDYONgLRUhLOv++m45bL4Pbey5sS
    l8pgpFe5cv3qVHuIaBqplE16zVDtWC5rv9rqL58QXjp8Pfxic/D2imCwARfA1l7p
    UvU1gPDH5cyC9GVqxCsRNDNQ/wKBgQDSbFOxoHc8zFh7M5ZmsSPKZ89IenASOmTp
    JNA+DrhBUWb9XYTwaOMDf1RGYp6AeFpyMiE7UEwB+rtPPTtKJj9NK77l3ev6FgJI
    xiu2X7vThaXWn8PLCN+kitLAMfSrcHUwMsjRrPSbYuwFJ0IZtraNxFjB2/Qo0WmI
    1YEcvFDbJQKBgQCN4L731CB+yCa7LKO0SVrA9I+6WpvBWQ44/OynCVfazAIXHMJI
    pZYa5G3W5TYH3xN40AkBq+XPcPKyg5z+gAfC5gftuUonAnKtU+lFOmeYgxzjbRYE
    pKWHxl6JjqFBjH3jvECh82wA61wvizOZzGCwP0z4tXB4Sk95+dhFvQ7keQKBgAoS
    d1scRDjbyyxyhrN5rS3mFCzy92RX+TaTtYgS6kzuGZDtJgzf6GXldWI9HDsoB6RJ
    s/+D02+Q0eB0HN9qv0LxYhzcp4v7+7YCDluXb4Urc4m3cgbI8POOVZIvkfeW1XUu
    KSCoN7ksXgHNJEPY1BorGNiGr8Q4aeXL2ndGqFQlAoGBAILSaafJ1jrYvIUJosWV
    oQjr0oIV7iXmYRJAB4B4XvoDUjNQBF6/tIhg4TrIyVzQN+w9h7J5taTNzcnWm89L
    OsgIjdMVE3L4c3v7eNkdVTqnxvo+fEKEggd6gpMq7Xor1f09nY/IQZo4LTz/XyEl
    hJMlh/+Gls16oxTQoHldL3w6
    -----END PRIVATE KEY-----
  jwt-public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz6nSQ0mkeF3KTHvdXVmY
    k2Pxt0qNPpcTdRWYfPuhThorFdNUW2gzWyfFlo0/S9tCSVhd71M3dNN220S94QN+
    kcoqF2V5FDlOWpAsVb6Rjp5yoeyNB94VXwMegdmRA2eLhG89ncgHu7vsPjxoAgce
    LRbOHYYypSUKdYruCObBKDqS0JO8vzqg80bnm2xmGk5gEKjSha2DXx3hyAMSfnOG
    1GE/r8W35472kq1X04zm2iuoCCSwifiSi5GF4Lr1seLibprai9uctkhEO2TJeHol
    1sEiPXLSDu5XOIAhzUrHLjx3tzpeYdLSyGwhlq0DOluy6hDAl/JR/GzEgEuNBWTZ
    2wIDAQAB
    -----END PUBLIC KEY-----
  profile-service-url: "http://profile-service.backend.svc.cluster.local:7000"
kind: ConfigMap
metadata:
  name: services-config
  namespace: backend