apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: backend
  labels:
    app: gateway
spec:
  type: LoadBalancer
  ports:
    - port: 7002
      name: gateway
      targetPort: 8002
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: backend
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: antonnv22/gatewayservice:0.0.2
          name: gateway
          env:
            - name: JWT_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: jwt-public-key
            - name: PROFILE_SERIVCE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: profile-service-url
          ports:
            - containerPort: 8002
          imagePullPolicy: IfNotPresent